# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PaddleMyWay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PaddleMyWay
  pod 'FirebaseDatabase'
  pod 'FirebaseAuth'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftRangeSlider'
  pod 'HCSStarRatingView'
  
  pod 'SDWebImage'
  pod 'Toast', '~> 4.0.0'
  pod 'SideMenu'
  
end
